directories:
  output: dist-electron
  buildResources: build
appId: com.todoapp.native
productName: To-Do App
copyright: 2026 Navjot
files:
  - filter:
      - dist
      - main.cjs
      - package.json
win:
  target: msi
  executableName: ToDoApp
  icon: public/logo-512.png
msi:
  oneClick: false
  perMachine: true
  shortcutName: To-Do App
  createDesktopShortcut: true
  createStartMenuShortcut: true
  runAfterFinish: false
electronVersion: 41.1.0
